<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lulu Retail | Where The World Comes To Shop</title>
    <meta name="description" content="Where the world comes to shop.">
    <link rel="icon" href="{{ asset('LuluLogo.svg') }}"><link rel="stylesheet" href="{{ asset('lulu-public.css') }}">
</head>
<body class="lulu-site">
<header class="lulu-header" id="top"><div class="lulu-container lulu-nav">
    <a class="lulu-brand" href="#top" aria-label="Lulu Retail home"><img src="{{ asset('LuluLogo.svg') }}" alt="Lulu Retail"></a>
    <button class="lulu-menu-toggle" type="button" aria-label="Toggle navigation"><span>☰</span></button>
    <nav class="lulu-nav-links" aria-label="Primary navigation">
        <a href="#about">About Us</a><a href="#businesses">Businesses</a><a href="#global">Global operations</a><a href="#impact">Impact</a><a href="#news">Media</a><a href="#careers">Careers</a><a href="{{ route('investors') }}">Investors</a><a class="lulu-nav-contact" href="#footer">Contact us</a>
    </nav><a class="lulu-search-link" href="#news" aria-label="Explore latest news">↗</a>
</div></header>
<main>
<section class="lulu-hero"><video class="lulu-hero-video" autoplay loop muted playsinline poster="https://imageio.forbes.com/specials-images/imageserve/67189a6c6fa7cba3cd2ed1ff/0x0.jpg?fit=bounds&amp;format=jpg&amp;height=1200&amp;width=2400"><source src="https://www.luluretail.com/media/frnlqrjj/lulu-retail-web-banner-min.mp4" type="video/mp4"></video><div class="lulu-hero-overlay"></div><div class="lulu-container lulu-hero-content"><p class="lulu-kicker">Where the world comes to shop</p><h1 class="lulu-banner-title">Where The World<br>Comes To Shop</h1><a class="lulu-light-button" href="{{ route('investors') }}"><span>Investor Relations</span><i>→</i></a></div><div class="lulu-scroll-note"><span>Scroll to explore</span>↘</div></section>
<section class="lulu-section lulu-intro lulu-facts-section lulu-reveal is-visible" data-reveal id="about"><div class="lulu-container"><h2 class="lulu-facts-title">Highlights</h2><div class="lulu-facts">
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/ilak12dj/area.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>1.38 Million</strong><small>sq.m</small></div><span>Total Retail Space</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/zdjg5yrv/food.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>680</strong><small>K+</small></div><span>Daily Shoppers</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/w5tbxl0w/shops.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>267</strong></div><span>Multi-format Stores</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/at1jqzh1/storage.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>200</strong><small>K+</small></div><span>Active SKUs</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/ksyfl40r/employees.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>52</strong><small>K+</small></div><span>Employees</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/etedskx1/globe.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>6</strong></div><span>Country Retail Operations</span></div></div>
    <div class="lulu-fact"><img src="https://www.luluretail.com/media/wfahin25/sourcing.svg" alt=""><div class="lulu-fact-content"><div class="lulu-fact-counter"><strong>85</strong></div><span>Global Sourcing Operations</span></div></div>
</div><p class="lulu-caption">*All figures as at FY2025.</p></div></section>
<section class="lulu-businesses-section lulu-reveal" data-reveal id="businesses"><div class="lulu-businesses-pattern"></div><div class="lulu-container"><div class="lulu-businesses-title"><span class="lulu-red-tag"></span><h2>Businesses</h2></div><div class="lulu-sector-bento">
    <a class="lulu-sector-card" href="#businesses"><img src="https://www.luluretail.com/media/cb4fto2w/lulu-retail.jpg?width=1100&height=700&format=webp&quality=90" alt="Lulu retail store"><div class="lulu-sector-caption"><h3>Retail</h3><p>Lulu Hypermarkets &amp; Lulu Express Stores</p><i>→</i></div></a>
    <a class="lulu-sector-card" href="#businesses"><img src="https://www.luluretail.com/media/wfwdsqya/import-distribution-bento-img.jpg?width=1100&height=700&format=webp&quality=90" alt="Lulu wholesale distribution"><div class="lulu-sector-caption"><h3>Wholesale</h3><p>Y International, Al Tayeb Distribution &amp; Al Tayeb Cold Stores</p><i>→</i></div></a>
</div></div></section>
<section class="lulu-section lulu-businesses"><div class="lulu-container"><div class="lulu-section-label"><span></span> Our businesses</div><div class="lulu-heading-row"><h2>Scale built<br><em>around people</em></h2><p>Our retail and wholesale platforms work together to deliver variety, quality and dependable supply at scale.</p></div><div class="lulu-business-grid"><article class="lulu-business-card lulu-business-featured"><div class="lulu-card-image"></div><div class="lulu-card-copy"><span>01 / Retail</span><h3>Lulu Hypermarkets<br>&amp; Lulu Express</h3><a href="#global">→</a></div></article><article class="lulu-business-card lulu-business-dark"><div class="lulu-card-copy"><span>02 / Wholesale</span><h3>Global<br>distribution</h3><p>A sourcing and logistics network that keeps quality products moving reliably.</p><a href="#global">→</a></div></article></div></div></section>
<section class="lulu-global lulu-reveal" data-reveal id="global"><div class="lulu-container"><div class="lulu-global-presence"><div class="lulu-global-copy"><h3>Global Presence</h3><p>From its homebase in the UAE, Lulu has branched out to more than 25 countries, where it enhances and enriches the lives of millions of people every day.</p></div><h4>85 Global Sourcing Operations</h4><div class="lulu-retail-map"><img src="https://www.luluretail.com/media/o3wct1dm/retail-map-min.svg" alt="Lulu Retail global sourcing map"></div><ul class="lulu-presence-note"><li class="on-ground">19 on-the-ground</li><li>66 other sourcing countries</li></ul></div></div></section>
<section class="lulu-section lulu-news lulu-reveal" data-reveal id="news"><div class="lulu-container"><div class="lulu-news-heading"><div><div class="lulu-section-label"><span></span> Latest updates</div><h2>News</h2></div><a class="lulu-light-button lulu-news-button" href="#news"><span>View More</span>→</a></div><div class="lulu-news-grid">@foreach ([['31 Aug 2026','Lulu expands presence in the holy city; opens new hypermarket in Madinah','https://www.luluretail.com/media/ryhh4i0v/lulu-madinah.jpg?width=1700&height=700&format=webp&quality=60'],['27 Aug 2026','Petromin and Lulu Sign MoU to Launch 10 SWFT Lulu Stores Across Saudi Arabia','https://www.luluretail.com/media/icin5ouw/petromin-lulu_1.jpg?width=600&height=400&format=webp&quality=60'],['12 Aug 2026','Lulu expands its presence in Kuwait; Opens new store at Jaber mall','https://www.luluretail.com/media/z4yp0n3p/kuwait_jabermall_lulu-100kb.jpg?width=600&height=400&format=webp&quality=60'],['11 Aug 2026','UAE President visits Lulu Hypermarket and Mushrif Mall, meets Yusuffali M.A. and senior officials of Lulu Group.','https://www.luluretail.com/media/ncphvn1k/visit-of-hh-sheikh-mohamed-bin-zayed-al-nahyan-to-lu​​lu-hypermarket-mushrif-mall_groupphoto.jpeg?width=600&height=400&format=webp&quality=60']] as $index => $item)<a class="lulu-news-card {{ $index === 0 ? 'is-featured' : '' }}" href="#news"><div class="lulu-news-image" style="background-image:url('{{ $item[2] }}')"></div><div class="lulu-news-copy"><span>{{ $item[0] }}</span><h3>{{ $item[1] }}</h3></div></a>@endforeach</div></div></section>
<section class="lulu-impact lulu-reveal" data-reveal id="impact"><div class="lulu-impact-image"></div><div class="lulu-container lulu-impact-content"><div class="lulu-section-label"><span></span> Growing with our communities</div><h2>Growth<br><em>with purpose</em></h2><p>Our strength comes from the trust of the communities we serve.</p><a class="lulu-light-button" href="#careers">Our commitments →</a></div></section>
<section class="lulu-careers lulu-reveal" data-reveal id="careers"><div class="lulu-container lulu-careers-inner"><div><div class="lulu-section-label"><span></span> Build what comes next</div><h2>Grow your career<br><em>with Lulu</em></h2></div><a class="lulu-round-arrow" href="#footer">→</a></div></section>
</main><footer class="lulu-footer" id="footer"><div class="lulu-container"><div class="lulu-footer-top"><a class="lulu-brand" href="#top"><img src="{{ asset('LuluLogo.svg') }}" alt="Lulu Retail"></a><p>Where the world<br><em>comes to shop.</em></p></div><div class="lulu-footer-links"><div><strong>Useful links</strong><a href="#about">About us</a><a href="#businesses">Businesses</a><a href="#global">Global operations</a></div><div><strong>Connect</strong><a href="{{ route('investors') }}">Investor relations</a><a href="#careers">Careers</a><a href="#footer">Contact us</a></div></div><div class="lulu-footer-bottom"><span>© {{ date('Y') }} Lulu Retail Holdings PLC</span><span>Privacy policy &nbsp; Terms of use</span><span>Made for everyday life</span></div></div></footer>
<script>
const menuButton=document.querySelector('.lulu-menu-toggle'), navigation=document.querySelector('.lulu-nav-links');
menuButton?.addEventListener('click',()=>navigation?.classList.toggle('is-open'));
const revealSections=document.querySelectorAll('[data-reveal]');
if ('IntersectionObserver' in window) {
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.18});
    revealSections.forEach(section=>observer.observe(section));
} else {
    revealSections.forEach(section=>section.classList.add('is-visible'));
}
</script>
</body></html>
