<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Investor Relations | Lulu Retail</title><meta name="description" content="Investor Relations"><link rel="icon" href="{{ asset('LuluLogo.svg') }}"><link rel="stylesheet" href="{{ asset('lulu-public.css') }}"><style>.investors-login-card{transition:height .3s ease,padding .3s ease}.investors-login-card.password-step{height:245px}.investors-login-card.password-step .investor-identity-step{display:none}.investors-login-card.password-step .investors-login-terms{margin-top:17px!important}</style></head>
<body class="investors-page"><header class="lulu-header investors-header"><div class="lulu-container lulu-nav"><a class="lulu-brand" href="{{ route('public.home') }}"><img src="{{ asset('LuluLogo.svg') }}" alt="Lulu Retail"></a><nav class="lulu-nav-links"><a href="{{ route('public.home') }}#about">About Us</a><a href="{{ route('public.home') }}#businesses">Businesses</a><a href="{{ route('public.home') }}#global">Global Operations</a><a href="{{ route('public.home') }}#impact">Impact</a><a href="{{ route('public.home') }}#news">Media</a><a href="{{ route('public.home') }}#careers">Careers</a><a class="investors-active-nav" href="#overview">Investors</a><a class="lulu-nav-contact" href="#contact-ir">Contact Us</a></nav><div class="investors-header-end"><a href="#footer">العربية</a><a class="lulu-search-link" href="#quick-links" aria-label="Explore investor resources">↗</a></div></div></header>
<main><section class="investors-banner"><div class="investors-container"><h1>Investor Relations</h1><p>Welcome to Lulu Retail Investor Relations website.</p></div>
<div class="investors-login-card" id="investor-login"><form class="investors-login-form" method="post" action="{{ route('login.submit') }}" data-login-action="{{ route('login.submit') }}" data-register-action="{{ route('register.partner') }}">@csrf
<div class="investor-identity-step"><a class="investors-apple-button" href="{{ route('login.google') }}"><svg class="investors-apple-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M17.05 20.28c-.98.95-2.05.8-3.08.35-1.09-.46-2.09-.48-3.24 0-1.44.62-2.2.44-3.06-.35C2.79 15.25 3.51 7.59 9.05 7.31c1.35.07 2.29.74 3.09.8 1.2-.24 2.35-.93 3.63-.84 1.54.12 2.7.74 3.46 1.88-3.18 1.9-2.43 6.1.49 7.27-.58 1.53-1.33 3.05-2.67 3.86ZM12.03 7.25C11.88 4.97 13.73 3.1 15.86 3c.3 2.63-2.39 4.6-3.83 4.25Z"></path></svg><span>Continue with Apple</span></a><a class="investors-google-button" href="{{ route('login.google') }}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92a5.06 5.06 0 0 1-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"></path><path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"></path><path d="M5.84 14.09a6.6 6.6 0 0 1 0-4.18V7.07H2.18A11 11 0 0 0 1 12c0 1.78.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"></path><path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"></path></svg><span>Continue with Google</span></a><div class="investors-login-divider"><span>or</span></div></div>
<label class="sr-only" for="investor-name">Full name</label><input id="investor-name" name="fullname" type="text" autocomplete="name" placeholder="Full name" hidden>
<label class="sr-only" for="investor-email">Email or username</label><input id="investor-email" name="email" type="text" autocomplete="username" placeholder="Email or username" required>
<label class="sr-only" for="investor-password">Password</label><input id="investor-password" class="investors-password-morph" name="password" type="password" autocomplete="current-password" placeholder="Password" hidden>
<input name="username" id="investor-username" type="hidden"><input name="password_confirmation" id="investor-password-confirmation" type="hidden">
<button class="investors-continue-button" type="submit">Continue</button></form>
@if ($errors->any())<p class="investors-login-error" role="alert">{{ $errors->first() }}</p>@endif
<button type="button" class="investors-mode-button" id="investor-mode">Create an account</button><p class="investors-login-terms">By continuing, you agree to our <a href="#terms">Terms of Service</a>, <a href="#privacy">Privacy Policy</a> and <a href="#cookies">Cookie Use</a>.</p></div></section>
<div class="investors-ticker" aria-label="Lulu Retail market information"><div class="investors-ticker-track">@for ($i=0;$i<3;$i++)<span class="instrument instrument_131227"><strong class="name">Lulu Retail Holdings</strong><span class="ticker-value"><span class="ticker-title">Last Price </span><b>0.95</b> AED</span><span class="ticker-value"><span class="ticker-title">Change </span><b class="ticker-negative">0.00 / -0.11%</b></span><span class="ticker-value"><span class="ticker-title">Volume </span><b>4,587,021</b></span><span class="ticker-date">04/09/2026 14:55</span></span>@endfor</div></div><div class="investors-breadcrumb"><div class="investors-container">Home <span>→</span> Investor Relations</div></div>
<section class="investors-intro" id="overview"><div class="investors-container investors-intro-grid"><div class="investors-intro-content"><h2>Where The World Comes To Shop</h2><img src="https://www.luluretail.com/media/ujmbkd4i/investors-lulu-hp.jpg?width=1000&height=600&format=webp&quality=90" alt="Lulu Retail store"><div class="investors-copy"><p>Lulu is a home-grown GCC retail champion, proudly operating for 50 years in the GCC. Founded in the UAE in 1974, we have strategically expanded across the GCC.</p><p>We are the largest full-line pan-GCC retailer, with a strong omni-channel presence including 267 stores operating across three formats, as well as a rapidly growing online presence.</p><p>We are well positioned for further growth, driven by store growth, operational efficiencies, private label, loyalty and online growth.</p></div></div><div class="investors-facts"><div class="investors-facts-grid">@foreach ([['267 Stores','Across all Six GCC Countries'],['680 K+','Daily Shoppers'],['85','Sourcing Countries'],['$7.9 Bn','Sales (4.1% YOY Growth)'],['$782 Mn','EBITDA (9.9% margin)'],['29.8%','Higher-Margin Private Label Sales']] as $fact)<article><strong>{{ $fact[0] }}</strong><span>{{ $fact[1] }}</span></article>@endforeach</div><em>*All figures are for FY2025</em></div></div></section>
<section class="investors-quick-links" id="quick-links"><div class="investors-container"><div class="investors-section-heading"><span>Explore</span><h2>Investor resources</h2></div><div class="investors-link-grid"><a href="#overview"><strong>Investment Highlights</strong><span>↗</span></a><a href="#overview"><strong>Factsheet</strong><span>↗</span></a><a href="#contact-ir"><strong>Announcements</strong><span>↗</span></a></div></div></section>
<section class="investors-contact" id="contact-ir"><div class="investors-container investors-contact-grid"><div><span>Get in touch</span><h2>Contact IR</h2><p>For enquiries and additional information, please get in touch with our Investor Relations team.</p></div><address><strong>Investor Relations Enquiries</strong><p>Lulu Retail Investor Relations</p><a href="mailto:investor.relations@ae.lulumea.com">investor.relations@ae.lulumea.com</a></address><address><strong>Registered Office</strong><p>Y Tower Building<br>Al Nahyan - E25<br>Abu Dhabi, United Arab Emirates</p></address></div></section></main>
<footer class="investors-footer" id="footer"><div class="investors-container"><a class="investors-footer-logo" href="{{ route('public.home') }}"><img src="{{ asset('LuluLogo.svg') }}" alt="Lulu Retail"></a><p>© {{ date('Y') }} Lulu Retail Holdings PLC</p></div></footer>
<script>
const card=document.querySelector('.investors-login-card'), form=card?.querySelector('form'), modeButton=document.querySelector('#investor-mode'), nameInput=document.querySelector('#investor-name'), email=document.querySelector('#investor-email'), password=document.querySelector('#investor-password'), continueButton=document.querySelector('.investors-continue-button'), username=document.querySelector('#investor-username'), confirmation=document.querySelector('#investor-password-confirmation'); let mode='login',step='identity';
function sync(){const passwordStep=step==='password';nameInput.hidden=mode==='login'||!(!passwordStep&&mode==='register');password.hidden=!passwordStep;email.hidden=passwordStep;card.classList.toggle('investors-password-step',passwordStep);card.style.height=passwordStep?'245px':'';card.querySelector('.investor-identity-step').style.display=passwordStep?'none':'';continueButton.textContent='Continue';continueButton.classList.toggle('investors-password-morph',passwordStep);form.action=mode==='login'?form.dataset.loginAction:form.dataset.registerAction;}
form?.addEventListener('submit',e=>{if(step==='identity'){e.preventDefault();if(!email.value.trim())return;step='password';sync();password.focus();return;}if(mode==='register'){username.value=(email.value.split('@')[0]||email.value).trim();confirmation.value=password.value;}});
modeButton?.addEventListener('click',()=>{mode=mode==='login'?'register':'login';step='identity';modeButton.textContent=mode==='login'?'Create an account':'Already have an account? Sign in';sync();});sync();
</script></body></html>
